service:
  name: races
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  profile: serverless-admin

package:
  include:
    - functions/**
    - models/**
    - services/**

functions:
  getRaces:
    handler: functions/read.getRaces
    events:
      - http:
          method: get
          path: /races
